// ─────────────────────────────────────────────
// src/lib/constants.js
// Single source of truth for brand + menu data
// ─────────────────────────────────────────────

export const BRAND = {
  name: "Teatings",
  tagline: "Tea · Eat · Meet",
  phone: "+919666836335",
  phoneDisplay: "+91 96668-36335",
  email: "courtyard@anterafood.in",
  address: "Ground Floor, #152, 9th Main Road, 6th Sector, HSR Layout, Bengaluru — 560102",
  addressShort: "#152, 9th Main Rd, HSR Layout, Bengaluru",
  hours: "Open every day · 9:00 AM – 11:00 PM",
  instagram: "https://instagram.com/teatings_cafe",
  instagramHandle: "@teatings_cafe",
  waMessage: encodeURIComponent("Hi, I'd like to reserve a table at Teatings!"),
  mapEmbed:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3888.8261!2d77.6382!3d12.9121!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae1499e7bcfe9d%3A0x1!2s152%2C+9th+Main+Rd%2C+6th+Sector%2C+HSR+Layout%2C+Bengaluru%2C+Karnataka+560102!5e0!3m2!1sen!2sin!4v1",
}

// localStorage key used across menu page + admin
export const MENU_STORAGE_KEY = "teatings_menu"

// Categories derived at runtime from menu data — but define the order here
export const CATEGORY_ORDER = [
  "All Day Breakfast",
  "Teas & Wellness",
  "Mains & Bowls",
  "Favourites",
  "Mocktails",
]

export const FILTERS = ["Full Meal", "Light Dishes", "Sweet", "Caffeine"]

// Seed data — written to localStorage by admin on first load if empty
export const SEED_MENU = [
  {
    id: 1,
    name: "Mushroom Omelette",
    price: 220,
    description: "Farm eggs, sautéed mushrooms, herbs, sourdough toast.",
    label: "veg",
    category: "All Day Breakfast",
    filters: ["Full Meal"],
    img: "/images/mushroom-omelette.jpeg",
  },
  {
    id: 2,
    name: "Avocado Toast",
    price: 240,
    description: "Smashed avo, cherry tomatoes, chilli flakes, multigrain.",
    label: "veg",
    category: "All Day Breakfast",
    filters: ["Light Dishes"],
    img: "/images/avocado-toast.jpeg",
  },
  {
    id: 3,
    name: "Pancake Stack",
    price: 260,
    description: "Buttermilk pancakes, maple syrup, fresh berries.",
    label: "veg",
    category: "All Day Breakfast",
    filters: ["Sweet"],
    img: "/images/pancake-stack.jpeg",
  },
  {
    id: 4,
    name: "Hibiscus Bloom",
    price: 160,
    description: "Dried hibiscus, rose petals, hint of honey.",
    label: "veg",
    category: "Teas & Wellness",
    filters: ["Light Dishes", "Caffeine"],
    img: "/images/hibiscus-bloom.jpg",
  },
  {
    id: 5,
    name: "Blue Pea Lemonade",
    price: 180,
    description: "Butterfly pea flower, lemon, jaggery.",
    label: "veg",
    category: "Teas & Wellness",
    filters: ["Light Dishes", "Sweet"],
    img: "/images/blue-pea.jpg",
  },
  {
    id: 6,
    name: "Lavender Chamomile",
    price: 170,
    description: "Calming herbed blend, served hot or iced.",
    label: "veg",
    category: "Teas & Wellness",
    filters: ["Light Dishes"],
    img: "/images/lavender-chamomile.jpg",
  },
  {
    id: 7,
    name: "Tulasi Green",
    price: 150,
    description: "Holy basil, green tea, ginger.",
    label: "veg",
    category: "Teas & Wellness",
    filters: ["Light Dishes", "Caffeine"],
    img: "/images/tulasi-green.jpg",
  },
  {
    id: 8,
    name: "Buddha Bowl",
    price: 320,
    description: "Quinoa, roasted veg, tahini dressing, sesame seeds.",
    label: "veg",
    category: "Mains & Bowls",
    filters: ["Full Meal", "Light Dishes"],
    img: "/images/buddha-bowl.jpg",
  },
  {
    id: 9,
    name: "Pesto Pasta",
    price: 340,
    description: "House-made basil pesto, parmesan, cherry tomatoes.",
    label: "veg",
    category: "Mains & Bowls",
    filters: ["Full Meal"],
    img: "/images/pesto-pasta.jpg",
  },
  {
    id: 10,
    name: "Chicken Steak",
    price: 420,
    description: "Herb-marinated breast, seasonal sides, chimichurri.",
    label: "nonveg",
    category: "Mains & Bowls",
    filters: ["Full Meal"],
    img: "/images/chicken-steak.jpg",
  },
  {
    id: 11,
    name: "Turkish Dawn",
    price: 380,
    description: "Spiced tuna, cucumber, avocado, toasted flatbread.",
    label: "nonveg",
    category: "Favourites",
    filters: ["Full Meal"],
    img: "/images/turkish-dawn.jpg",
  },
  {
    id: 12,
    name: "Caesar Salad",
    price: 300,
    description: "Romaine, house Caesar dressing, croutons, parmesan.",
    label: "egg",
    category: "Favourites",
    filters: ["Light Dishes"],
    img: "/images/caesar-salad.jpg",
  },
  {
    id: 13,
    name: "Meaty Meat Burger",
    price: 460,
    description: "Double patty, caramelised onion, special sauce, brioche.",
    label: "nonveg",
    category: "Favourites",
    filters: ["Full Meal"],
    img: "/images/meaty-burger.jpg",
  },
  {
    id: 14,
    name: "Hibiscus Mocktail",
    price: 200,
    description: "Hibiscus, sparkling water, basil, lime.",
    label: "veg",
    category: "Mocktails",
    filters: ["Sweet", "Light Dishes"],
    img: "/images/hibiscus-mocktail.jpg",
  },
  {
    id: 15,
    name: "Mint Cooler",
    price: 180,
    description: "Fresh mint, lemon, soda, jaggery syrup.",
    label: "veg",
    category: "Mocktails",
    filters: ["Sweet", "Light Dishes"],
    img: "/images/mint-cooler.jpg",
  },
  {
    id: 16,
    name: "Watermelon Fizz",
    price: 210,
    description: "Fresh watermelon, ginger beer, chaat masala rim.",
    label: "veg",
    category: "Mocktails",
    filters: ["Sweet", "Light Dishes"],
    img: "/images/watermelon-fizz.jpg",
  },
]
